import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Client from "@/shared/layout/client";
import Navbar from "@/components/shared/navbar";
import Query from "@/components/shared/layout/query";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Base Landing",
  description: "Generated by Jee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Query>
          <Client>
            <Navbar />
            {children}
          </Client>
        </Query>
      </body>
    </html>
  );
}
